# Generated by Django 2.1.3 on 2018-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20181103_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_detail',
            field=models.TextField(null=True),
        ),
    ]
